### ISSUE TITLE
Name is confusing - shouldn't it be called azure-active-directory-connector?

### ISSUE THREAD

**Issue by steveculshaw** [CoditEU/active-directory-connector#57]
The name is confusing !

Shouldn't it be called azure-active-directory-connector?

It's not an on-premise "Active Directory" connector

**Comment by tomkerkhove** [comment]
It's actually an API for querying Graph API using Azure Active Directory Application authentication, but it's no longer maintained anymore; sorry.

I'll archive the repo to reflect that.
